name: Publish to Cloudflare
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.3.4
      - name: actions/setup-node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "16.1.0"
      - name: npm install
        uses: jaid/action-npm-install@master
      - name: Build
        run: npm run build:prod
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: self
          BRANCH: cloudflare
          FOLDER: dist/package/production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}