name: Publish to Pages
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.3.4
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: self
          BRANCH: pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}