name: Publish to Pages
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.3.4
      - name: Move content to subdirectory # https://github.com/s0/git-publish-subdir-action/issues/31
        run: mkdir pages && shopt -s extglob dotglob && mv !(pages) pages && shopt -u dotglob
        shell: bash
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: self
          BRANCH: pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: pages