name: Publish to Surge
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout
        uses: actions/checkout@v2.1.0
      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.13.0"
      - name: npm install
        uses: jaid/action-npm-install@master
      - name: Install globals
        run: npm install --global surge package-field-cli
      - name: Build
        run: npm run build:prod
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.5.0
        env:
          REPO: self
          BRANCH: cloudflare
          FOLDER: build/package/production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}